# Generated by Django 5.2.6 on 2025-10-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_DB',
            fields=[
                ('Car_name', models.CharField(max_length=20)),
                ('Fuel_efficient', models.FloatField()),
                ('Color', models.CharField(max_length=10)),
                ('Price', models.IntegerField()),
                ('CarID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
